---
- name: Debian - Ensure /etc/mysql/ exists.
  file:
    path: /etc/mysql
    owner: root
    group: root
    mode: 0755
    state: directory

- name: "Debian - Ensure {{ mysql_config_path | dirname }} exists."
  file:
    path: "{{ mysql_config_path | dirname }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Debian - Ensure /etc/mysql/conf.d exists.
  file:
    path: /etc/mysql/conf.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: "Debian - Ensure {{ mysql_config_path }} is configured."
  template:
    src: my.cnf.j2
    dest: "{{ mysql_config_path }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart mysql

- name: Debian - Ensure MySQL python package is installed.
  apt:
    name: "{{ mysql_python_package }}"
    state: present

- name: Debian - Ensure MySQL packages are installed.
  apt:
    name: "{{ mysql_packages }}"
    state: present
  register: mysql_install_packages

- name: Debian - Ensure alternatives point to mysql.cnf.
  alternatives:
    name: my.cnf
    link: "/etc/mysql/mysql.cnf"
    path: "/etc/mysql/{{ mysql_provider }}.cnf"

- name: Debian - Post-installation.
  block:
    - name: Debian - Remove existing /root/.my.cnf.
      file:
        path: /root/.my.cnf
        state: absent

    - when: mysql_provider == "mariadb"
      block:
        - name: Debian - Check if extra configuration files are present.
          find:
            paths:
              - /etc/mysql/conf.d/
              - /etc/mysql/mariadb.conf.d/
          register: __mysql_extra_config_files

        - name: Debian - Remove the extra confguration files.
          file:
            path: "{{ item.path }}"
            state: absent
          loop: "{{ __mysql_extra_config_files.files }}"
          when: item.path != mysql_config_path

    - name: Debian - Ensure MySQL is started.
      service:
        name: "{{ mysql_service }}"
        state: started

  when: mysql_install_packages.changed
